# Generated by Django 3.1 on 2020-09-10 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qts_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad_listing',
            name='ad_status',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='ad_listing',
            name='promotion_duration',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='feedback',
            name='comments',
            field=models.TextField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='ad_type',
            name='Is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
