# Generated by Django 3.1 on 2020-09-09 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qts_api', '0002_payment_paid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paid_amount',
        ),
    ]
