# Generated by Django 3.1 on 2020-09-10 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qts_api', '0002_auto_20200910_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoted_ad_detail',
            name='starting_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='promoted_ad_detail',
            name='status',
            field=models.IntegerField(default=None),
        ),
    ]
