# Generated by Django 3.1 on 2020-09-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qts_api', '0003_remove_payment_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad_type',
            name='type_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
