# Generated by Django 3.1 on 2020-09-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qts_api', '0004_auto_20200910_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad_type',
            name='Is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
